services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-password}
      - POSTGRES_DB=db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U ${DATABASE_USERNAME:-postgres}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  motorcyclerentalsystem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: motorcyclerentalsystem
    ports:
      - "5001:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
